<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * User.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository
 */
class UserRepository extends EntityRepository
{
    /**
     * @param integer $id
     *
     * @return mixed
     */
    public function findFriendsToAdd($user)
    {
        $qb = $this->createQueryBuilder('u');
        $qb = $qb->where($qb->expr()->notIn('u.id', ':ids'))
            ->setParameter('ids', $user->getFriendIds());

        return $qb->getQuery()->getResult();
    }
}
